Healthcare Twitter Analytics
========================================================
## Sentiment Analysis: compare two approaches
```{r,echo=FALSE}
dir = 'C:/Users/GRFisher4/Documents/Introduction_to_Data_Science/Healthcare_Twitter_Analysis/healthcare_twitter_analysis'
setwd(dir)
source("~/Dropbox/R_functions/eda.R")
rm(list = setdiff(ls(), lsf.str())) # remove all but functions
opar = par(no.readonly=TRUE)
```

```{r,message=FALSE}
# see http://jeffreybreen.wordpress.com/2011/07/04/twitter-text-mining-r-slides/

# setup
# =====
source("score.sentiment.R")
hu.liu.pos = scan('positive-words.txt', what='character', comment.char=';')
hu.liu.neg = scan('negative-words.txt', what='character', comment.char=';')
pos.words = c(hu.liu.pos, 'upgrade')
neg.words = c(hu.liu.neg, 'wtf', 'wait', 'waiting', 'epicfail', 'mediocrity')

# examples
# ========
sample = c("You're awesome and I love you",
           "I hate and hate and hate. So angry. Die!",
           "Impressed and amazed: you are peerless in your achievement of unparalleled mediocrity.")
result = score.sentiment(sample, pos.words, neg.words)
result$score

score.sentiment(c("@Delta I'm going to need you to get it together. Delay on tarmac, delayed connection, crazy gate changes... #annoyed",
                 "Surprised and happy that @Delta helped me avoid the 3.5 hr layover I was scheduled for. Patient and helpful agents. #remarkable"),
pos.words, neg.words)$score

# Look at some tweets
# ===================
data = read.csv("Tweets_Celiac_sent.csv")
text = data$content

# create the sentiment score with the Jeffrey Breen method
scores = score.sentiment(text, pos.words, neg.words, .progress='none')

# append the AFINN sentiment scores
scores$AFINN = data$sentiment
rm(data,text)

grfsummary(scores)

# plot the two sentiment distributions
par(mfrow=c(1,2))
hist(scores$score,main='Breen Sentiment Scores',xlab='score',ylab='Frequency',xlim=c(-10,15))
hist(scores$AFINN,main='AFINN Sentiment Scores',xlab='score',ylab='Frequency',xlim=c(-10,15))

hist.density.box(scores$score,main='Breen Sentiment Scores')
hist.density.box(scores$AFINN,main='AFINN Sentiment Scores')

```