Healthcare Twitter Analytics
========================================================
### Look at the top ten hashtags and score
```{r,echo=FALSE}
dir = 'C:/Users/GRFisher4/Documents/Introduction_to_Data_Science/Healthcare_Twitter_Analysis/healthcare_twitter_analysis'
setwd(dir)
#source("~/Dropbox/R_functions/stem_plot.R")
#source("~/Dropbox/R_functions/eda.R")
#source("~/Dropbox/R_functions/lm_utilities.R")
rm(list = setdiff(ls(), lsf.str())) # remove all but functions
opar = par(no.readonly=TRUE)
```
```{r,message=FALSE}
file = 'Tweets_Celiac_hashtagsplit.csv'
data = read.csv(file)

hashtags     = subset(data, select = c(hashtag,score))
hashtag_freq = as.data.frame(table(hashtags$hashtag))
hashtag_freq = hashtag_freq[with(hashtag_freq, order(-Freq)), ]
hashtag_freq = hashtag_freq[1:10,]

data=data[as.character(data$hashtag) %in% as.character(hashtag_freq$Var1),]
data=droplevels(data)
```
```{r}

par(las=3)
barplot(hashtag_freq$Freq,main=paste("Top Ten Hashtag Frequency\n",file),ylab="Hashtag Frequency")
axis(side=1,labels=hashtag_freq$Var1,at=c(1,2,3,4,5,6,7,8,9,10),cex.axis=0.65)
```
```{r}
par(las=3)
plot(data$hashtag,data$score,main=paste("Distributions of Scores of Top Ten Hashtags\n",file),ylab="Score")
axis(side=1,cex.axis=0.65)
```

```{r,echo=FALSE}
par(opar)
rm(list = setdiff(ls(), lsf.str())) # remove all but functions
opar = par(no.readonly=TRUE)
```
